#.travis.yml for deBInfer

language: r
cache: packages
r_packages: covr
matrix:
 include:
   - os: osx
     r: release
     disable_homebrew: true
     sudo: required
     before_install:
      - sudo tlmgr update --self
      - sudo tlmgr install framed
      - sudo tlmgr install titling
   - os: osx
     disable_homebrew: true
     r: devel
     r_packages:
      - openssl
      - httr
      - covr
      - coda
      - deSolve
      - mvtnorm
      - PBSddesolve
      - plyr
      - RColorBrewer
      - truncdist
     sudo: required
     before_install:
      - curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
      - sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /
      - sudo tlmgr update --self
      - sudo tlmgr install framed
      - sudo tlmgr install titling
   - os: linux
     r: release
     sudo: required
   - os: linux
     r: devel
     sudo: required
 allow_failures:
  - os: osx
    r: devel
warnings_are_errors: true
after_success:
  - Rscript -e 'covr::codecov()'
