#.travis.yml for deBInfer

language: r
cache: packages
matrix:
 include:
   - os: linux
     r: release
   - os: linux
     r: devel
   - os: osx
     r: release
     before_install: sudo tlmgr install framed
   - os: osx
     r: devel
     before_install: sudo tlmgr install framed
warnings_are_errors: true
sudo: required
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
