# Sample .travis.yml for R projects

language: r
cache: packages
r:
 - release
 - devel
warnings_are_errors: true
sudo: required

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
