#.travis.yml for deBInfer

language: r
cache: packages
matrix:
 include:
   - os: linux
     r: release
     sudo: required
   - os: linux
     r: devel
     sudo: required
   - os: osx
     r: release
     sudo: required
     before_install: 
      - sudo tlmgr update --self
      - sudo tlmgr install framed
   - os: osx
     r: devel
     sudo: required
     before_install: 
      - sudo tlmgr update --self
      - sudo tlmgr install framed
warnings_are_errors: true
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
