#.travis.yml for deBInfer

language: r
cache: packages
r_packages: covr
matrix:
 include:
   - os: osx
     r: release
     sudo: required
     before_install:
      - sudo tlmgr update --self
      - sudo tlmgr install framed
      - sudo tlmgr install titling
   - os: osx
     r: devel
     r_packages:
      - covr
      - coda
      - deSolve
      - mvtnorm
      - PBSddesolve
      - plyr
      - RColorBrewer
      - truncdist
     sudo: required
     before_install:
      - sudo tlmgr update --self
      - sudo tlmgr install framed
      - sudo tlmgr install titling
   - os: linux
     r: release
     sudo: required
   - os: linux
     r: devel
     sudo: required
warnings_are_errors: true
#r_github_packages:
#  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
