#.travis.yml for deBInfer

language: r
cache: packages
os:
 - linux
 - osx
r:
 - release
 - devel
warnings_are_errors: true
sudo: required

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
