#.travis.yml for deBInfer

language: r
r_build_args: --compact-vignettes="gs+qpdf"
cache: packages
matrix:
 include:
   - os: osx
     r: release
     r_packages:
      - magick
     disable_homebrew: true
     sudo: required
     before_install:
      - sudo tlmgr update --self
      - sudo tlmgr install framed
      - sudo tlmgr install titling
   - os: osx
     disable_homebrew: false
     brew_packages: imagemagick
     r: devel
     r_packages:
      - magick
      - coda
      - deSolve
      - mvtnorm
      - PBSddesolve
      - plyr
      - RColorBrewer
      - truncdist
      - knitr
      - rmarkdown
      - testthat
      - microbenchmark
      - R.rsp
      - beanplot
     sudo: required
   - os: linux
     addons:
        apt:
          update: true
          packages:
            - libmagick++-dev
     r: release
     r_packages:
     - covr
     - magick
     sudo: required
   - os: linux
     addons:
        apt:
          update: true
          packages:
            - libmagick++-dev
     r: devel
     r_packages:
      - devtools
      - covr
      - magick
     sudo: required
     after_success: Rscript -e 'covr::codecov()'
 allow_failures:
        - os: osx
warnings_are_errors: true
